### ISSUE TITLE
bug in parzival-static-api/src/util/metadata-ms-page.xsl

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/parzival-static-api#7]
I noticed that [Textzeuge I](http://localhost:5173/textzeugen/i) does not display all the verses it should. I am relying here on https://dhbern.github.io/parzival-static-api/api/json/metadata-ms-page/i.json .
It doesn't pick up all the lines that there are.

Can you please look into that?

**Comment by flicksolutions** [comment]
I think I found the pattern:
your script doesn't pick up the `<pb />` that are inside a `<l>` tag. So whenever a page breaks in a line, the whole page is missing from the output json.

```
<l xml:id="i_47.28">do <lb/>
<pb xml:id="i001v"/>
                <cb xml:id="i001va"/>
wart auch er von hahmuret.</l>
```

is not picked up for example

**Comment by pdaengeli** [comment]
I think your assessment was spot on, @flicksolutions, and the [`descendant` instead of `child` axis](https://github.com/DHBern/parzival-static-api/commit/f0b4dccc5) did the trick.

<details><summary><code>diff</code></summary>

![image](https://github.com/user-attachments/assets/9b684748-e3f4-4902-8791-47c6b5055e5c)

```
        "47.25",
        "47.26",
        "47.27",
        "47.28"
      ]
    },
    {
      "id": "i001v",
      "iiif": "https:\/\/iiif.ub.unibe.ch\/image\/v3\/Parzival\/i001v.jpf\/info.json",
      "l": [
        "47.30",
        "47.29",
        "48.01",
        "48.02",
```
</details>

Available now at https://dhbern.github.io/parzival-static-api/api/json/metadata-ms-page/i.json etc.

**Comment by flicksolutions** [comment]
Thanks so much!
